const Map<String,String> en={
  'login':'Log In',
  'signUp':'Sign Up',
  'logout':'Log Out',
  'face':'Login With Facebook',
  'google':'Login With Google',
  'guest': 'Continue as a guest ->',
  'sucAccount':'You have successfully You have successfully created an account',
  'sucLog':'You have successfully logged in',
  'name':'Enter Your Name',
  'mail':'Enter Your Email',
  'pass':'Enter Your Password',
  'fPass':'Forgot Password?',
  'logFirst':'You should log in first',
  'welcome':"Welcome",
  'join':'Join our community',
  'resala':'Sign-up to get most out of elmmenus. Share your experience, follow favorite restaurants and more',
  'create':'CREATE ACCOUNT',
  'haveAccount':'ALREADY HAVE AN ACCOUNT',
  'delivery':'Delivery',
  'dine':'Dine out',
  'cart':'My Cart',
  'profile':'profile',
  'cong':'Congratulation',
  'sucOrder':'Your order has been executed successfully',
  'sucMeal':'The meal has been added successfully',
  'confirm':'Confirm order',
  'noItem':'No Items Added Yet',
  'missOut':'You\'re missing out \n You haven\'t place any orders yet',
  'discover':'Discover the best dishes around you and place your first order now',
  'dto':'Restaurants delivering to  ',
  'loc':'Nasr City , Cairo',
  'discNow':'I WANT TO DISCOVER AND ORDER NOW',
  'err':'Error',
  'ok':'Ok',
  'sandwich':'Sandwich',
  'small':'Small',
  'medium':'Medium',
  'large':'Large',
  'note':' Special instructions',
  'ex':'ex : don not add onion',
  'rest':'Restaurants',
  'search':'Find a Restaurant',
  'code':'50EGP off on your 1st order for a \n limited time on orders above 120 EGP   Use Code : FIRST50 ',
  'live':'Live Tracking',
  'payment':'Online Payment',
  'promo':'Accepts Promo',
  'offers':'Offers' ,
  'off':' % 30EGP on orders above 130 EGP',
  'true':'Your Cravings Come true',
  'dish':'Discover by dish',
  'orders':'Show All Orders',
  'meals':'all Meals',
  'hidden':'Hidden Game',
  'moods':'Discover by moods',
  'new':'New',
  'basket':'Add To Basket',
  'egp':'EGP'
};